name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake ninja-build

    - name: Clean build directory (if exists)
      run: rm -rf build

    - name: Configure CMake
      run: cmake -S . -B build -G Ninja

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: ctest --test-dir build --output-on-failure
